In [2]:
import numpy as np

In [6]:
ex_list = [4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7]
ex_list
len(ex_list)

12

In [199]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a
len(a)


12

How many negative numbers are there?

In [201]:
a[a < 0]

array([-2, -1, -6, -7])

In [200]:
len(a[a < 0])

4

How many positive numbers are there?



In [15]:
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [16]:
len(a[a > 0])

5

How many even positive numbers are there?



In [27]:
a[(a % 2 == 0) & (a > 0)]


array([ 4, 10, 12])

In [205]:
((a % 2 == 0) & (a > 0)).sum()

3

If you were to add 3 to each data point, how many positive numbers would there be?



In [30]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [33]:
a + 3
b = a + 3
b

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [34]:
b[b > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [35]:
len(b[b > 0])

10

If you squared each number, what would the new mean and standard deviation be?



In [42]:
a.mean(), a.std()
print(f'Mean: {a.mean()} | Standard Deviation: {a.std()}')

Mean: 3.0 | Standard Deviation: 8.06225774829855


In [39]:
a ** 2
c = a ** 2 
c

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [44]:
c.mean(), c.std()
print(f' New Mean: {c.mean()} | New Standard Devation: {a.std()}')

 New Mean: 74.0 | New Standard Devation: 8.06225774829855


A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. 



In [45]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [46]:
a.mean()

3.0

In [206]:
a - a.mean()
d = a - a.mean()
d

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [207]:
d.mean()

0.0

Calculate the z-score for each data point. Recall that the z-score is given by:



In [52]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [51]:
a.mean(), a.std()
print(f'Mean {a.mean()} | Standard Deviation {a.std()}')

Mean 3.0 | Standard Deviation 8.06225774829855


In [53]:
g = []

for item in a:
    g = item - 3 / 8.1
    print(g)


3.6296296296296298
9.62962962962963
11.62962962962963
22.62962962962963
-2.3703703703703702
-1.3703703703703705
-0.3703703703703704
-0.3703703703703704
-0.3703703703703704
-6.37037037037037
2.6296296296296298
-7.37037037037037


In [208]:
(a - a.mean() / a.std())

array([ 3.6278958,  9.6278958, 11.6278958, 22.6278958, -2.3721042,
       -1.3721042, -0.3721042, -0.3721042, -0.3721042, -6.3721042,
        2.6278958, -7.3721042])

# a is redefined

Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.



In [209]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]



Use python's built in functionality/operators to determine the following:


Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list


In [107]:
def sum_of_a(numbers):
    total = 0
    for number in numbers:
         total += number
    return total

sum_of_a(a)

55

In [210]:
sum(a)

55

Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list


In [113]:
min_of_a = min(a)
print(f'Min of a is: {min(a)}')

Min of a is: 1



Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [112]:
max_of_a = max(a)
print(f'Max of a is: {max(a)}')

Max of a is: 10



Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [117]:
mean_of_a = sum_of_a(a) / len(a) 
print(f'Mean of a = {sum_of_a(a) / len(a)}')

Mean of a = 5.5


Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together


In [125]:
def product_a(mylist):
    result = 1
    for i in mylist:
        result = result * i
    return result 

product_of_a = product_a(a)

product_of_a

3628800

Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [129]:
square_of_a = []
for i in a:
    square_of_a.append(i**2)

print(square_of_a)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [212]:
[i**2 for i in a]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers


In [131]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [214]:
odds_in_a = []
[i for i in a if i % 2 != 0]


[1, 3, 5, 7, 9]

Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [135]:
a
for i in a:
    if i % 2 == 0:
        print(i)

2
4
6
8
10



What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...


Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.


In [139]:
b = [  
    [3, 4, 5],
    [6, 7, 8]
]
np.array(b)
b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. Hint, you'll first need to make sure that the "b" variable is a numpy array**


In [141]:
sum_of_b = b.sum()
sum_of_b



33

Exercise 2 - refactor the following to use numpy. 


In [143]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 
min_of_b 


3

In [142]:
b.min()

3

Exercise 3 - refactor the following maximum calculation to find the answer with numpy.


In [144]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b


8

In [145]:
b.max()

8

Exercise 4 - refactor the following using numpy to find the mean of b


In [146]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b


5.5

In [147]:
b.mean()

5.5

Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.


In [148]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number


In [215]:
b.prod()

20160

Exercise 6 - refactor the following to use numpy to find the list of squares

In [ ]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


In [150]:
b **2

array([[ 9, 16, 25],
       [36, 49, 64]])



Exercise 7 - refactor using numpy to determine the odds_in_b


In [ ]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


In [216]:
b[b % 2 == 1]

array([3, 5, 7])



Exercise 8 - refactor the following to use numpy to filter only the even numbers


In [ ]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)


In [217]:
b[b % 2 == 0]

array([4, 6, 8])


Exercise 9 - print out the shape of the array b.


In [155]:
b.shape

(2, 3)


Exercise 10 - transpose the array b.


In [219]:
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [221]:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])


Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)


In [218]:
b.reshape(1, 6)

array([[3, 4, 5, 6, 7, 8]])

In [222]:
np.reshape(b, (6,))

array([3, 4, 5, 6, 7, 8])


Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


In [227]:
np.reshape(b, (6, 1)).tolist()

[[3], [4], [5], [6], [7], [8]]

In [160]:

## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
np.array(c)
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


 HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.


Exercise 1 - Find the min, max, sum, and product of c.


In [161]:
c.min(), c.max(), c.sum(), 

(1, 9, 45)


Exercise 2 - Determine the standard deviation of c.


In [162]:
c.std()

2.581988897471611


Exercise 3 - Determine the variance of c.


In [166]:
c.var()

6.666666666666667


Exercise 4 - Print out the shape of the array c


In [163]:
c.shape

(3, 3)


Exercise 5 - Transpose c and print out transposed result.


In [228]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])


Exercise 6 - Get the dot product of the array c with c. 


In [190]:
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])


Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [230]:
(c * c.T).sum()

261


Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [231]:

np.product(c * c.T)

131681894400

In [251]:

## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
np.array(d)
d = np.array(d)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])


Exercise 1 - Find the sine of all the numbers in d


In [250]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])


Exercise 2 - Find the cosine of all the numbers in d


In [249]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])


Exercise 3 - Find the tangent of all the numbers in d


In [248]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])


Exercise 4 - Find all the negative numbers in d


In [247]:
d[d < 0]

array([-90, -30, -45, -45])


Exercise 5 - Find all the positive numbers in d


In [246]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])


Exercise 6 - Return an array of only the unique numbers in d.


In [244]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])


Exercise 7 - Determine how many unique numbers there are in d.


In [245]:
len(np.unique(d))

11


Exercise 8 - Print out the shape of d.


In [252]:
d.shape

(3, 6)


Exercise 9 - Transpose and then print out the shape of d.


In [255]:
trans_d = d.T
trans_d.shape

(6, 3)

In [256]:
d.T.shape

(6, 3)

Exercise 10 - Reshape d into an array of 9 x 2

In [257]:
d.reshape(9, 2)


array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])